### ISSUE TITLE
Adding faces to the original theme

### ISSUE THREAD

**Issue by fleutot** [greduan/emacs-theme-gruvbox#135]
I am missing faces for `magit-diff-file-heading`, and made local copies of the files I found relevant, where I intend to test changes.

I don't understand how `gruvbox-light-soft-theme.el` finds `gruvbox.el`, and I can't make it happen in my local copies.

Details:

I copied `gruvbox-light-soft-theme.el` from my local elpa install to my `~/.emacs.d/themes/gruvbox-light-softer-theme.el`, and elpa's `gruvbox.el` to `~/.emacs.d/themes/my-gruvbox.el`.

The file renames are to make sure I use the copies in `~/.emacs.d/themes`, rather than the theme in `~/.emacs.d/elpa`.

Changes I made from `elpa/gruvbox-theme-20190210.1403/gruvbox.el` to `themes/my-gruvbox.el`:
- Added `magit-diff-file-heading` 
- Modified `provide` call to `(provide 'my-gruvbox)`

Changes I made from `elpa/gruvbox-theme-20190210.1403/grubox-ligt-soft-theme.el` to `themes/gruvbox-light-softer-theme.el`:
- modified `require` to `my-gruvbox`
- modified first parameter of `gruvbox-deftheme` to `gruvbox-light-softer`
- modified first parameter of `custom-theme-set-variables` to `gruvbox-light-softer`
- modified parameter of `provide-theme` to `gruvbox-light-softer`

After changing the name of the macro `gruvbox-deftheme` to `my-gruvbox-deftheme` (both call and definition, of course), I noticed that the macro was not found. 

So my question is: when I `load-theme` my local `themes/gruvbox-light-softer` theme, why doesn't `(require 'my-gruvbox)` manage to define the macro `my-gruvbox-deftheme`, or complains at `require`? How do I make this `require` find the macro?

Emacs 25.1.1, but this is obviously a problem between keyboard and chair on my side.
Thanks!

**Comment by kaofelix** [comment]
Hi @fleutot,

I can't directly answer your question, but I can share my workflow for testing changes and contributing changes to `gruvbox.el. I don't have a `my-gruvbox.el`, I have the latest version from Melpa installed on my emacs and I have this repo cloned on my machine with a remote for my fork included.

I take the following steps:

1. open `gruvbox.el` 
2. make the changes I want
3. call `eval-buffer`: this will cause all the definitions in the current file to replace the existing definitions in the Emacs runtime
4. "refresh" the theme: I'm using my own function here that I use to toggle between light and dark variants to do this "refresh", but under the hood it's calling `disable-theme` over active themes and then calling `load-theme` with either `gruvbox-light-hard` or `gruvbox-dark-soft` depending on which one was active before. Maybe just `M-x load-theme RET gruvbox-some-variant` might work fine for you
5. repeat 2 to 4 as necessary
6. commit and push changes to my remote
7. open a PR from Github

The `eval-buffer` (or `load-file` if you prefer) part should work fine with your `my-gruvbox.el` as long as all the definitions in there keep the same name as the original. When you reload your theme it will use the new definitions that you evaluated from your file.

I wanted to try fancier setups, but they didn't work for me. I'm using cask + pallet for dependency management and cask has a [link](https://cask.readthedocs.io/en/latest/guide/usage.html#cask-link) option for using local source for a package instead of a version from the package repos, but I couldn't make it work. In the end I settled for the approach above since it's simple and conveient enough for me for now.

I hope this is helpful for you and happy theming! :)

**Comment by fleutot** [comment]
Running `eval-buffer` on every change of my `my-gruvbox.el` did the trick. I naively thought that reloading the theme itself would reevaluate the other file through `require`. Thanks!
