### ISSUE TITLE
Light version

### ISSUE THREAD

**Issue by lf94** [greduan/emacs-theme-gruvbox#45]
Hey,

Could you please merge @vyp's light version of gruvbox? His gruvbox-theme.el is a fork of this project so it could make it easier.

I would greatly appreciate it. You've done a great job porting this theme over to emacs!

Thanks,

Lee

**Comment by greduan** [comment]
@lf94 sorry a bit of context please? I thought you'd be from this issue https://github.com/greduan/emacs-theme-gruvbox/issues/32 but you're not.

**Comment by lf94** [comment]
@vyp has "forked" your code and added the light version of gruvbox. An issue is that he might have problems getting his extremely similar version of his gruvbox theme onto MELPA. The other issue is that yours is well maintained, but has no light version.

His fork his here https://github.com/vyp/gruvbox-emacs

I tried it merging them myself but it came out all weird.

**Comment by jasonm23** [comment]
We would like to have the gruvbox projects merge and have all collaborators join the one project so that Gruvbox just got support and development in one place.

So far though, these other project owners haven't contacted us.

We will eventually just implement the features any other Gruvbox theme on Emacs provides.

I will accept any pull request which provides an alternative light version, which is using the canonical Vim Gruvbox light palette.

**Comment by vyp** [comment]
I'm willing to do this or support this at some point sorry for my lack of response to this, you guys have caught me at a bad time unfortunately.

**Comment by jasonm23** [comment]
Hi, thank you for contacting us.

I am happy to help out if there are tasks you can give me.

I'll hold on until we hear from you again.

**Comment by jasonm23** [comment]
@vyp we are prepping to overhaul the gruvbox theme using autothemer 

You can look at my sample work at https://github.com/emacsfodder/emacs-theme-darktooth/tree/use-autothemer - (for the Darktooth theme.)

The way we have the palette organised in Gruvbox makes it very easy to migrate

**Comment by vyp** [comment]
Autothemer doesn't have an appropriate license though.

**Comment by jasonm23** [comment]
That can be fixed.

**Comment by mekeor** [comment]
Autothemer has a license now. It's GPLv3.

**Comment by jasonm23** [comment]
It sure does :+1:

**Comment by jasonm23** [comment]
@vyp just a side note.

Autothemer is going to mean that implementing new palettes is significantly easier.

All the face attribute to palette value mapping will be uniform across all palettes.  I don't see this as a problem.

I'll try and wrap all this up next week.

**Comment by vyp** [comment]
@jasonm23 No yep I understand and appreciate it! Also as side note sorry I know it's been a long time here without any resolution but just have other priorities for the moment. But just want to say that I do still plan on getting around to this if no one else does so beforehand.

**Comment by jasonm23** [comment]
@vyp @lf94 @mekeor 

I've pushed a new branch [dark-light](https://github.com/greduan/emacs-theme-gruvbox/tree/dark-light)

This is using Emacs built in support for dark / light backgrounds so I'll need to figure something out that does this nicely.

There is a new custom var gruvbox-variant which can be set to dark or light and it will trigger the change when the theme is first loaded, but I think it would be nicer to just commands:

- `gruvbox-theme-dark`
- `gruvbox-theme-light`  

Maybe a toggle would be nice but I'll let users ask for that.

Please  take a look, I think this is one of the more interesting points about autothemer (since this is a built in Emacs feature which is otherwise a real pain to use.)

**Comment by smypf** [comment]
@jasonm23 Could you explain how one goes about swapping between the two? Searching for a potential solution I came across https://github.com/sellout/emacs-color-theme-solarized/issues/167#issuecomment-145324305 but that didn't work the way I expected it to.

**Comment by jasonm23** [comment]
It's been a while since I looked, but it was frustratingly difficult to make it work reliably.

Auto themer helped a lot, but I didn't get the dark light switching I had hoped for.  Not a dead end, but more to be done.

**Comment by metalelf0** [comment]
Hi all, is there any update on this? I'm a big fan of this theme and newcomer to emacs. If I can help anyhow I'd be glad to.

**Comment by jasonm23** [comment]
I did some work on this and had disappointing results.  I can release a dark on light version a little easier though.

I will try and look at this again at the weekend

**Comment by VanLaser** [comment]
The light version was also my Vim favourite, hoping it gets landed to Emacs soon :)

**Comment by greduan** [comment]
@jasonm23 I'd like to propose an idea, let me know if you already tried it.

It seems that the approaches that are common/popular for adding dark/light versions involve having some flag that switches and based on that some color variables change.

Instead of that, how about implementing two different `gruvbox-theme-dark.el` and `gruvbox-theme-light.el`? Exactly same code for both, just the colors used change.

I realize this doesn't follow the famous DRY, but it's worth considering on the merit of its simplicity I think.

**Comment by jasonm23** [comment]
No longer an issue.  An implementation of gruvbox light is now part of this theme.
