### ISSUE TITLE
Colors not the same as original

### ISSUE THREAD

**Issue by BerberBerthold** [greduan/emacs-theme-gruvbox#93]
The colors are not the same as in the original vim gruvbox theme. They are slightly different. I can change them manually, but shouldn't you have the original colors as default?

Or am I not understanding something?

**Comment by martijnat** [comment]
I just checked and the colors in this theme seem to be the same as those defined for the vim version.

One possible difference is if you use one application in a 256-color terminal (very common) and the other as a gui program. The 256-color pallete can only give you an approximation so the colors will be slightly different.

Could you provide an example of where the themes colors differ?

**Comment by jasonm23** [comment]
@BerberBerthold note that while the palette used is the same as Vim Gruvbox, the syntax coloring will not match in Vim and Emacs themes.

**Comment by BerberBerthold** [comment]
I know that the syntax coloring is different. I am specifically talking about the colors.

Example: In the original, colors 2 and 10, the greens, are:
#98971A
#B8BB26
While in this Emacs port, the color #B8BB26 is present, though not the color #98971A.
This is similar with some of the other colors.

I don't know exactly how Emacs colors work compared to the terminal, or vim, but some of the original shades of colors are not present at all in this Emacs port.

**Comment by martijnat** [comment]
@BerberBerthold Thank you for the details.

In the light variants, the colors match the vim theme. In the dark variants, the neutral color variants are mismatched. Neutral colors are the same shade as the bright colors.

I suspect the colors were copied from an earlier version of gruvbox and not updated.

Fixing this in code can be done quite easily but changes the look of many faces and changes overall look of the theme noticeably. I will make a pull request but I am not sure if changing the colors is an obvious improvement

**Comment by martijnat** [comment]
https://github.com/greduan/emacs-theme-gruvbox/pull/94 was created to fix this issue.

A lot of code was touched to fix this so it might take a while before it is merged

**Comment by jasonm23** [comment]
Thank you for clarifying @BerberBerthold

Please comment on the PR #94 

@martijnat thanks for looking into this, I'm not sure there's a worthwhile improvement in the color change either.

If the goal of this theme is to be a 100% port of the Vim theme, we don't have a choice but to match palette.

AFAIC This goal is soft, mainly because we cannot match syntax coloring with Vim.

I would prefer to leave the PR open for a while.  This will give anyone motivated to do so, a chance to canvas for support or rejection of the change.

My vote would not be a decider, and I would imagine that @greduan doesn't want to dictate either.  

However I feel that Emacs Gruvbox is its own theme in  ways and there's a lot of installed users who are happy with the palette as is.

I'd be highly reluctant to merge the change without a significant popular indication that it's desirable.
